baseurl = "https://docs.prefech.com/"
languageCode = "en-us"
title = "Prefech Documentation"
theme = "hugo-theme-learn"
metadataformat = "yaml"
enableGitInfo = false

[params]
  description = "Prefech Documentation"
  author = "JokeDevil"
  showVisitedLinks = true
  themeVariant = "blue"
  editURL = "https://github.com/Prefech/PrefechDocs/tree/master/content/"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Prefech Documentation"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
    name = "<i style='color: #2196f3;' class='fab fa-github'></i> GitHub"
    url = "https://github.com/Prefech/"
    weight = 10

[[Languages.en.menu.shortcuts]]
    name = "<i style='color: #7289da;' class='fab fa-discord'></i> Discord"
    url = "https://discord.gg/prefech"
    weight = 30

[[Languages.en.menu.shortcuts]]
    name = "<i style='color: #f96854;' class='fab fa-patreon'></i> Patreon"
    url = "https://www.patreon.com/prefech"
    weight = 40

[[Languages.en.menu.shortcuts]]
    name = "<i style='color: #2196f3;' class='fas fa-globe'></i> Website"
    url = "https://prefech.com/"
    weight = 50

[[Languages.en.menu.shortcuts]]
    name = "<i style='color: #2196f3;' class='fab fa-twitter'></i> Twitter"
    url = "https://twitter.com/Prefech_/"
    weight = 60
